cookie:
  expiry_days: 2
  key: avcdef
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: Admin
      name: Admin
      password: $2b$12$xz8StMRUS3e7wUM7G0raYuk6vapX6AnOi9aAVWUghfwfx./zPXfTu
    analyst:
      email: analyst@test.de
      name: Analyst
      password: $2b$12$VGUjzcKGPGGj/z.vZYZs5.Dti3n2Zo.9iYk4EnH0DrGE2EmXjTOAS
    mel:
      email: melsby@gmail.com
      name: Mel
      password: $2b$12$DfnrBaYRnH43mjjbLBigHOo3rTlj8rB.sHdWfjJeF4./nQS7MOzyK
    pascal:
      email: pascal@badzura.de
      name: Pascal
      password: $2b$12$M5HJIOP5v72a6oxj9t5xF.z77YaeRiPxejFfAPyFI..VkbLwB3/H2
    user:
      email: User
      name: User
      password: $2b$12$2S7eTDjJSIa7ZSsSowPxCO20YmaXX/kTyFx5laEpKWRRdxTMkGi0O
preauthorized:
  emails: pascal@badzura.de rainhard@schwarz.de tobias@meier.de
